LESSC = lessc
COFFEE = coffee
JADE = jade

vpath %.less . style styles
vpath %.css . style styles
vpath %.coffee . script scripts
vpath %.js . script scripts
vpath %.jade . view views template templates
vpath %.html . view views template templates

.SECONDEXPANSION:
%.css: $(notdir $$*).less | $$(@D)/
	$(LESSC) $< $@

%.js: $(notdir $$*).coffee | $$(@D)/
	$(COFFEE) -p $< > $@

%.html: $(notdir $$*).jade | $$(@D)/
	$(JADE) -Pp $(dir $<) $< > $@

%/:
	mkdir -p $@
