// Generated by CoffeeScript 1.3.3
(function() {
  var mapping, search, youtube;

  ($('#search')).on('keyup', function(event) {
    var val;
    val = ($(this)).val();
    return setTimeout((function() {
      if (($('#search')).val() === val) {
        return ($('#search')).trigger('search');
      }
    }), 200);
  });

  mapping = function(fn, from, to) {
    return function(obj) {
      var ff, tf, _results;
      _results = [];
      for (ff in obj) {
        tf = obj[ff];
        _results.push((from(ff))[fn]((to(tf))[fn]()));
      }
      return _results;
    };
  };

  youtube = function(youtube, offset) {
    return "https://gdata.youtube.com/feeds/api/videos?v=2&max-results=10&start-index=" + offset + "&q=" + youtube;
  };

  search = function(query, offset, fn) {
    return $.get(youtube(query, offset), function(data) {
      return fn.call(($(data)).find('entry').map(function() {
        var $d, $r, result, video;
        data = this;
        result = ($('#preload > .result')).clone();
        $d = function(query) {
          return ($(data)).find(query).first();
        };
        $r = function(query) {
          return ($(result)).find(query).first();
        };
        video = ($d('content')).attr('src');
        (mapping('text', $r, $d))({
          h1: 'title',
          '.author': 'author > name',
          '.date': 'published',
          p: 'description'
        });
        ($r('img')).attr('src', ($d('thumbnail')).attr('url'));
        ($r('a')).attr('href', ($d('link[rel=alternate]')).attr('href'));
        result.on('click.loadVideo', function(event) {
          return ($(this)).off('click.loadVideo').find('iframe').attr('src', video);
        });
        return result;
      }));
    });
  };

  ($('#search')).on('search', function(event) {
    return search(($(this)).val(), 1, function() {
      ($('#results')).empty();
      return this.each(function() {
        return ($(this)).appendTo('#results');
      });
    });
  });

  ($('body')).on('click', '#results > .result', function(event) {
    return ($(this)).toggleClass('open');
  });

  ($('#search')).val('skateboarding dog');

  ($('#search')).trigger('search');

  ($('#search')).focus();

}).call(this);
